package liferay.processes

import io.gatling.core.Predef._
import io.gatling.core.session
import io.gatling.http.Predef._

/**
 * A random navigation.
 */
object SiteMapRandom {

  def run() =
    randomSwitch(
      1.00 -> exec(http("Accueil").get("/accueil")),
      1.00 -> exec(http("suberbe news").get("/actualites/suberbe-news")),
      1.00 -> exec(http("Alertes et notifications").get("/alertes-et-notifications")),
      1.00 -> exec(http("Assurance Cybersecurite").get("/assurance-cybersecurite")),
      1.00 -> exec(http("Complementaire sante prevoyance pour salaries").get("/complementaire-sante-prevoyance-pour-salaries")),
      1.00 -> exec(http("Complementaire sante prevoyance pour tns").get("/complementaire-sante-prevoyance-pour-tns")),
      1.00 -> exec(http("formations GLI").get("/pages-a-trier/formations-gli")),
      1.00 -> exec(http("Actualites").get("/galian-et-moi/actualites")),
      1.00 -> exec(http("Actualites Corporate").get("/galian-et-moi/actualites/corporate")),
      1.00 -> exec(http("Actualites reglementation").get("/galian-et-moi/actualites/reglementation")),
      1.00 -> exec(http("Espaces").get("/galian-et-moi/espaces")),
      1.00 -> exec(http("Espace agent commercial").get("/galian-et-moi/espaces/espace-agent-commercial")),
      1.00 -> exec(http("Espace agent commercial - attestation ").get("/galian-et-moi/espaces/espace-agent-commercial/attestation")),
      1.00 -> exec(http("Renouveler mon contrat").get("/galian-et-moi/espaces/espace-agent-commercial/renouveler-mon-contrat")),
      1.00 -> exec(http("Espace ca").get("/galian-et-moi/espaces/espace-ca")),
      1.00 -> exec(http("Bibliotheque").get("/galian-et-moi/espaces/espace-ca/bibliotheque")),
      1.00 -> exec(http("L-agenda").get("/galian-et-moi/espaces/espace-ca/l-agenda")),
      1.00 -> exec(http("Les ag des chambres").get("/galian-et-moi/espaces/espace-ca/les-ag-des-chambres")),
      1.00 -> exec(http("Les membres du ca").get("/galian-et-moi/espaces/espace-ca/les-membres-du-ca")),
      1.00 -> exec(http("Espace ca, masterpage").get("/galian-et-moi/espaces/espace-ca/masterpage")),
      1.00 -> exec(http("Reporting administrateur").get("/galian-et-moi/espaces/espace-ca/reporting-administrateur")),
      1.00 -> exec(http("Audit sociétaire").get("/galian-et-moi/espaces/espace-chambre/audit-societaire")),
      1.00 -> exec(http("Informations chambre").get("/galian-et-moi/espaces/espace-chambre/informations-chambre")),
      1.00 -> exec(http("Informations societaires").get("/galian-et-moi/espaces/espace-chambre/informations-societaires")),
      1.00 -> exec(http("Les attestations non delivrees").get("/galian-et-moi/espaces/espace-chambre/les-attestations-non-delivrees")),
      1.00 -> exec(http("Les journees de prevention rcp").get("/galian-et-moi/espaces/espace-chambre/les-journees-de-prevention-rcp")),
      1.00 -> exec(http("Liste des chiffres d'affaire/Espace Chambre").get("/galian-et-moi/espaces/espace-chambre/liste-des-chiffres-d-affaires")),
      1.00 -> exec(http("Liste des clients assurances").get("/galian-et-moi/espaces/espace-chambre/liste-des-clients-assurances")),
      1.00 -> exec(http("Liste des montants de garantie ti-gi").get("/galian-et-moi/espaces/espace-chambre/liste-des-montants-de-garantie-ti-gi")),
      1.00 -> exec(http("Liste des sinistres rcp").get("/galian-et-moi/espaces/espace-chambre/liste-des-sinistres-rcp")),
      1.00 -> exec(http("Espace delegue").get("/galian-et-moi/espaces/espace-delegue")),
      1.00 -> exec(http("Bibliotheque delegues").get("/galian-et-moi/espaces/espace-delegue/bibliotheque-delegues")),
      1.00 -> exec(http("FAQ delegues").get("/galian-et-moi/espaces/espace-delegue/faq-delegues")),
      1.00 -> exec(http("Informations Chambre").get("/galian-et-moi/espaces/espace-delegue/informations-chambre")),
      1.00 -> exec(http("Informations societaires").get("/galian-et-moi/espaces/espace-delegue/informations-societaires")),
      1.00 -> exec(http("Audit societaire").get("/galian-et-moi/espaces/espace-delegue/informations-societaires/audit-societaire")),
      1.00 -> exec(http("Modifications juridiques et mouvements de garantie").get("/galian-et-moi/espaces/espace-delegue/informations-societaires/modifications-juridiques-et-mouvements-de-garantie")),
      1.00 -> exec(http("Suivi societaire").get("/galian-et-moi/espaces/espace-delegue/informations-societaires/suivi-societaire")),
      1.00 -> exec(http("Journee des delegues").get("/galian-et-moi/espaces/espace-delegue/journee-des-delegues")),
      1.00 -> exec(http("Les attestations non delivrees").get("/galian-et-moi/espaces/espace-delegue/les-attestations-non-delivrees")),
      1.00 -> exec(http("Les journees de prevention rcp").get("/galian-et-moi/espaces/espace-delegue/les-journees-de-prevention-rcp")),
      1.00 -> exec(http("Liste des chiffres d'affaires/Espace delegue").get("/galian-et-moi/espaces/espace-delegue/liste-des-chiffres-d-affaires")),
      1.00 -> exec(http("Liste des clients assurances").get("/galian-et-moi/espaces/espace-delegue/liste-des-clients-assurances")),
      1.00 -> exec(http("Liste des delegues").get("/galian-et-moi/espaces/espace-delegue/liste-des-delegues")),
      1.00 -> exec(http("Liste des montants de garantie ti-gi").get("/galian-et-moi/espaces/espace-delegue/liste-des-montants-de-garantie-ti-gi")),
      1.00 -> exec(http("Liste des sinistres-rcp").get("/galian-et-moi/espaces/espace-delegue/liste-des-sinistres-rcp")),
      1.00 -> exec(http("Espace groupe").get("/galian-et-moi/espaces/espace-groupe")),
      1.00 -> exec(http("Acces aux extranets des structures du societaire").get("/galian-et-moi/espaces/espace-groupe/acces-aux-extranets-des-structures-du-societaire")),
      1.00 -> exec(http("Espace mandant").get("/galian-et-moi/espaces/espace-mandant")),
      1.00 -> exec(http("Mon espace question").get("/galian-et-moi/espaces/mon-espace-question")),
      1.00 -> exec(http("Adresser une reclamation").get("/galian-et-moi/espaces/mon-espace-question/adresser-une-reclamation")),
      1.00 -> exec(http("Poser une question").get("/galian-et-moi/espaces/mon-espace-question/poser-une-question")),
      1.00 -> exec(http("Questions-Reponses").get("/galian-et-moi/espaces/mon-espace-question/questions-reponses")),
      1.00 -> exec(http("Evenements et formations").get("/galian-et-moi/evenements-et-formations")),
      1.00 -> exec(http("Nos partenaires").get("/galian-et-moi/nos-partenaires")),
      1.00 -> exec(http("Presentation valeurs et engagements").get("/galian-et-moi/presentation-valeurs-et-engagements")),
      1.00 -> exec(http("Decouvrir galian").get("/galian-et-moi/presentation-valeurs-et-engagements/decouvrir-galian")),
      1.00 -> exec(http("Kit media").get("/galian-et-moi/presentation-valeurs-et-engagements/kit-media")),
      1.00 -> exec(http("Valeurs et engagements").get("/galian-et-moi/presentation-valeurs-et-engagements/valeurs-et-engagements")),
      1.00 -> exec(http("Vos administrateurs").get("/galian-et-moi/presentation-valeurs-et-engagements/vos-administrateurs")),
      1.00 -> exec(http("Vos delegues").get("/galian-et-moi/presentation-valeurs-et-engagements/vos-delegues")),
      1.00 -> exec(http("Informations legales").get("/informations-legales")),
      1.00 -> exec(http("Mandataire galian").get("/mandataire-galian")),
      1.00 -> exec(http("Mes factures").get("/mes-factures")),
      1.00 -> exec(http("Mes informations").get("/mes-informations")),
      1.00 -> exec(http("Mes informations financieres").get("/mes-informations-financieres")),
      1.00 -> exec(http("Missions conseils").get("/missions-conseils")),
      1.00 -> exec(http("Modifier mot de passe").get("/modifier-mot-de-passe")),
      1.00 -> exec(http("Assurances de mes Clients").get("/mon-agence/assurances-de-mes-clients")),
      1.00 -> exec(http("Assur bail").get("/mon-agence/assurances-de-mes-clients/assur-bail")),
      1.00 -> exec(http("mes produits d'assurance").get("/mon-agence/assurances-de-mes-clients/mes-produits-d-assurance")),
      1.00 -> exec(http("Outils Marketing").get("/mon-agence/assurances-de-mes-clients/outils-marketing")),
      1.00 -> exec(http("Renouvellement orias").get("/mon-agence/assurances-de-mes-clients/renouvellement-orias")),
      1.00 -> exec(http("Suivi performance portefeuille").get("/mon-agence/assurances-de-mes-clients/suivi-performance-portefeuille")),
      1.00 -> exec(http("Assurances de mon agence").get("/mon-agence/assurances-de-mon-agence")),
      1.00 -> exec(http("Garantie Financiere").get("/mon-agence/assurances-de-mon-agence/garantie-financiere")),
      1.00 -> exec(http("versalis").get("/mon-agence/assurances-de-mon-agence/versalis")),
      1.00 -> exec(http("Mes collaborateurs").get("/mon-agence/mes-collaborateurs")),
      1.00 -> exec(http("Mes agents commerciaux").get("/mon-agence/mes-collaborateurs/mes-agents-commerciaux")),
      1.00 -> exec(http("Mes salaries").get("/mon-agence/mes-collaborateurs/mes-salaries")),
      1.00 -> exec(http("mes contacts galian").get("/mon-agence/mes-contacts-galian")),
      1.00 -> exec(http("Performance de mon cabinet").get("/mon-agence/performance-de-mon-cabinet")),
      1.00 -> exec(http("Ma position marche").get("/mon-agence/performance-de-mon-cabinet/ma-position-marche")),
      1.00 -> exec(http("Ma region").get("/mon-agence/performance-de-mon-cabinet/ma-region")),
      1.00 -> exec(http("Mon diagnostic financier").get("/mon-agence/performance-de-mon-cabinet/mon-diagnostic-financier")),
      1.00 -> exec(http("Mon diagnostic metier").get("/mon-agence/performance-de-mon-cabinet/mon-diagnostic-metier")),
      1.00 -> exec(http("MRH").get("/mrh")),
      1.00 -> exec(http("Multiris Bureaux").get("/multiris-bureaux")),
      1.00 -> exec(http("PNO").get("/pno")),
      1.00 -> exec(http("Gestion").get("/produits-et-services/gestion")),
      1.00 -> exec(http("Axelis").get("/produits-et-services/gestion/axelis")),
      1.00 -> exec(http("Gestion multiris").get("/produits-et-services/gestion/multiris")),
      0.25 -> exec(http("Multiris Bailleur").get("/produits-et-services/gestion/multiris-bailleur")),
      0.25 -> exec(http("Mutua").get("/produits-et-services/gestion/mutua")),
      0.25 -> exec(http("saisonis").get("/produits-et-services/gestion/saisonis")),
      0.25 -> exec(http("Versalis").get("/produits-et-services/gestion/versalis")),
      0.25 -> exec(http("Nos services et offres d'accompagnement").get("/produits-et-services/nos-services-et-offres-d-accompagnement")),
      0.25 -> exec(http("Pour mes mandants").get("/produits-et-services/pour-mes-mandants")),
      0.25 -> exec(http("Assur bail").get("/produits-et-services/pour-mes-mandants/assur-bail")),
      0.25 -> exec(http("Souscription").get("/produits-et-services/pour-mes-mandants/assur-bail/souscription")),
      0.25 -> exec(http("Garantie financiere et rcp").get("/produits-et-services/pour-mon-agence/garantie-financiere-et-rcp")),
      0.25 -> exec(http("Produits d'assurances").get("/produits-et-services/produits-d-assurances")),
      0.25 -> exec(http("Services Galian").get("/produits-et-services/services-galian")),
      0.25 -> exec(http("Assistance juridique").get("/produits-et-services/services-galian/assistance-juridique")),
      0.25 -> exec(http("Bibliotheque juridique").get("/produits-et-services/services-galian/bibliotheque-juridique")),
      0.25 -> exec(http("Garantie financiere").get("/produits-et-services/services-galian/garantie-financiere")),
      0.25 -> exec(http("Juridissimo").get("/produits-et-services/services-galian/juridissimo")),
      0.25 -> exec(http("Prevoyance sante groupe").get("/produits-et-services/services-galian/prevoyance-sante-groupe")),
      0.25 -> exec(http("Prevoyance sante tns").get("/produits-et-services/services-galian/prevoyance-sante-tns")),
      0.25 -> exec(http("RCP acfimo iobsp").get("/produits-et-services/services-galian/rcp-acfimo-iobsp")),
      0.25 -> exec(http("RCP excess").get("/produits-et-services/services-galian/rcp-excess")),
      0.25 -> exec(http("RCP expert").get("/produits-et-services/services-galian/rcp-expert")),
      0.25 -> exec(http("services").get("/produits-et-services/services-galian/services")),
      0.25 -> exec(http("Bourse des transmissions").get("/produits-et-services/services-galian/services/bourse-des-transmissions")),
      0.25 -> exec(http("Cession de cabinet").get("/produits-et-services/services-galian/services/cession-de-cabinet")),
      0.25 -> exec(http("Mission conseil").get("/produits-et-services/services-galian/services/mission-conseil")),
      0.25 -> exec(http("Syndic").get("/produits-et-services/syndic")),
      0.25 -> exec(http("coprolis").get("/produits-et-services/syndic/coprolis")),
      0.25 -> exec(http("Domagis et eco domagis").get("/produits-et-services/syndic/domagis-et-eco-domagis")),
      0.25 -> exec(http("PNOS").get("/produits-et-services/syndic/pnos")),
      0.25 -> exec(http("Tous nos produits").get("/produits-et-services/tous-nos-produits")),
      0.25 -> exec(http("Transaction").get("/produits-et-services/transaction")),
      0.25 -> exec(http("RCP agent commercial").get("/produits-et-services/transaction/rcp-agent-commercial")),
      0.25 -> exec(http("Zen immo").get("/produits-et-services/transaction/zen-immo"))
    )
}